In [4]:
#Code to help get all csv files into a useable format for making into figures
import pandas as pd
import numpy as np
import sys
import os
thisDir = os.path.expanduser('~/Desktop/MSC_Alexis/analysis/')
#outDir = thisDir + 'output/mLmax/results/ridge/'
outDir = thisDir + 'output/mLmin/results/ridge/'
subDir=outDir+'subNetwork/'
ranDir=outDir+'randomIdx/'

taskList=['mixed','mem','motor']
subList=['MSC01','MSC02','MSC03','MSC04','MSC05','MSC06','MSC07','MSC10']
#all permutations of features
rand_CV=pd.DataFrame()
rand_SS=pd.DataFrame()
rand_DS=pd.DataFrame()
rand_BS=pd.DataFrame()
frameList=[5,10,15,20,25,30,40,50,60,70,80,90,100,125,150,175,200,225,250,275,300,325,350]
features=[10,20,30,40,50,60,70,80,90,100,200,300,400,500,1000,1500,2000,2500,3000,4000,5000,10000,15000,20000,30000,40000,50000]
"""
for feat in features:
    #CV
    CVfile=pd.read_csv(ranDir+'CV/'+str(feat)+'.csv')
    CVfile.drop(columns='sub', inplace=True)
    CVfile=CVfile.melt(value_vars=['mixed', 'motor','mem'], var_name='Task', value_name='Accuracy')
    CVfile['Features']=feat
    rand_CV=pd.concat([rand_CV,CVfile])
    #SS
    SSfile=pd.read_csv(ranDir+'SS/'+str(feat)+'.csv')
    SSfile['Features']=feat
    rand_SS=pd.concat([rand_SS,SSfile])
    #DS
    DSfile=pd.read_csv(ranDir+'DS/'+str(feat)+'.csv')
    DSfile['Features']=feat
    rand_DS=pd.concat([rand_DS,DSfile])
    #BS
    BSfile=pd.read_csv(ranDir+'BS/'+str(feat)+'.csv')
    BSfile['Features']=feat
    rand_BS=pd.concat([rand_BS,BSfile])
    
rand_CV.to_csv(ranDir+'CV/all.csv')
rand_SS.to_csv(ranDir+'SS/all.csv')
rand_DS.to_csv(ranDir+'DS/all.csv')
rand_BS.to_csv(ranDir+'BS/all.csv')


#allFolds
#DS
motor=pd.DataFrame()
mixed=pd.DataFrame()
mem=pd.DataFrame()
for train in subList:
    for test in subList:
        if train==test:
            continue
        #motor
        tmpmotor=pd.read_csv(outDir+'acc/DS/folds/'+train+test+'motor.csv',usecols=[1,2,3])
        motor=pd.concat([motor,tmpmotor])
        #mixed
        tmpmix=pd.read_csv(outDir+'acc/DS/folds/'+train+test+'mixed.csv',usecols=[1,2,3])
        mixed=pd.concat([mixed,tmpmix])
        #mem
        tmpmem=pd.read_csv(outDir+'acc/DS/folds/'+train+test+'mem.csv',usecols=[1,2,3])
        mem=pd.concat([mem,tmpmem])
        
motMix=pd.merge(motor,mixed,on=['train', 'test'])        
DS_folds=pd.merge(motMix,mem,on=['train', 'test'])   
DS_folds.rename(columns={'mixed':'Mixed','motor':'Motor','mem':'Memory'}, inplace=True)
DS_violin=pd.melt(DS_folds, id_vars=['train','test'],value_vars=['Motor','Mixed','Memory'], var_name='task', value_name='acc')
DS_violin.to_csv(outDir+'acc/DS/folds/allFolds.csv', index=False)

#SScondensed 
for sub in subList:
    sub_tmp=pd.DataFrame()
    for train in taskList:
        for test in taskList:
            if train==test:
                continue
            tmp=pd.read_csv(outDir+'acc/SS/folds/'+train+test+sub+'.csv',usecols=[1,2,3])
            sub_tmp=pd.concat([sub_tmp,tmp])
    #return sub_tmp
    sub_tmp.to_csv(outDir+'acc/SS/folds/'+sub+'.csv', index=False)

#BScondensed 
for train_sub in subList:
    subF=pd.DataFrame()
    for test_sub in subList:
        if train_sub==test_sub:
            continue
        for train_task in taskList:
            for test_task in taskList:
                if train_task==test_task:
                    continue
                tmp=pd.read_csv(outDir+'acc/BS/folds/'+train_sub+test_sub+train_task+test_task+'.csv', usecols=[1,2,3,4,5])
                subF=pd.concat([subF, tmp])
    subF.to_csv(outDir+'acc/BS/folds/'+train_sub+'.csv', index=False)
#SS once all folds per tasks are condensed into subs
SS=pd.DataFrame()
for sub in subList:
    tmp=pd.read_csv(outDir+'acc/SS/folds/'+sub+'.csv')
    tmp=pd.melt(tmp, id_vars=['train','test'], value_vars=[sub], var_name='sub', value_name='acc')
    SS=pd.concat([SS,tmp])
SS.to_csv(outDir+'acc/SS/folds/allFolds.csv', index=False)
#BS once all folds are condensed into subs
BS=pd.DataFrame()
subList=['MSC01','MSC02','MSC03','MSC04','MSC05','MSC06','MSC07','MSC10']
for sub in subList:
    tmp=pd.read_csv(outDir+'acc/BS/folds/'+sub+'.csv')
    BS=pd.concat([BS,tmp])
BS.to_csv(outDir+'acc/BS/folds/allFolds.csv', index=False)
#reformedFolds CV in results.py code


"""

#frames 
fCV=pd.DataFrame()
fBS=pd.DataFrame()
fSS=pd.DataFrame()
fDS=pd.DataFrame()
for f in frameList:
        #CV
    CVfile=pd.read_csv(outDir+'frames/CV/'+str(f)+'CV.csv')
    fCV=pd.concat([fCV,CVfile])
    #SS
    SSfile=pd.read_csv(outDir+'frames/SS/'+str(f)+'SS.csv')
    fSS=pd.concat([fSS,SSfile])
    #DS
    DSfile=pd.read_csv(outDir+'frames/DS/'+str(f)+'DS.csv')
    fDS=pd.concat([fDS,DSfile])
    #BS
    BSfile=pd.read_csv(outDir+'frames/BS/'+str(f)+'BS.csv')
    fBS=pd.concat([fBS,BSfile])

In [5]:
fCV.to_csv(outDir+'/frames/CV/allFrames.csv',index=False)
fSS.to_csv(outDir+'/frames/SS/allFrames.csv',index=False)
fDS.to_csv(outDir+'/frames/DS/allFrames.csv',index=False)
fBS.to_csv(outDir+'/frames/BS/allFrames.csv',index=False)

In [3]:
fSS.head()

       acc  train  frames
0  0.75000  MSC01       5
1  0.67500  MSC02       5
2  0.70625  MSC03       5
3  0.65000  MSC04       5
4  0.87500  MSC05       5

In [6]:
fDS.head()

     acc  train   test  frames
0  0.580  MSC02  MSC04       5
1  0.705  MSC02  MSC05       5
2  0.605  MSC02  MSC06       5
3  0.555  MSC02  MSC07       5
4  0.525  MSC04  MSC02       5

In [7]:
fBS.head()

     acc  train   test  frames analysis
0  0.555  MSC02  MSC04       5       BS
1  0.575  MSC02  MSC05       5       BS
2  0.555  MSC02  MSC06       5       BS
3  0.550  MSC02  MSC07       5       BS
4  0.525  MSC04  MSC02       5       BS